os: linux
# dist: trusty
language: cpp
compiler: gcc

branches:
  only:
    - master
    - develop

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - graphviz
      - g++-6
env:
  global:
    - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6

script:
  - mkdir cmake-build
  - cd cmake-build && cmake ..
  - make all test 
