os: linux
dist: trusty
language: cpp
compiler: gcc

branches:
  only:
    - master
    - develop

addons:
  apt:
    packages:
      - doxygen
      - graphviz
   
script:
  - mkdir cmake-build
  - cd cmake-build && cmake ..
  - make all test 
