# autho: Herbert Koelman
# created on: 1/6/2019
os: linux

# use Ubuntu Xenial (version 16)
# This comes with cmake 3.11 which is required to build GoogleTest
dist: xenial
language: cpp
compiler: gcc

env:
  CODECOV_TOKEN="6fa05a9c-1a01-4123-b726-d493275017cd"

# Run travis on these branches only...
branches:
  only:
    - master
    - develop

addons:
  sonarcloud:
    organization: "herbertkoelman-github"

  apt:
    packages:
      - doxygen
      - graphviz

matrix:
  include:
    - name: sonar code quality checks
      env:
        BUILD_DIRECTORY=cmake-gcov-build
        CMAKE_COMMAND_LINE_ARGS="-DGCOV=yes"
        MAKE_TARGETS="all test"
    - name: coverage jobs
      env:
        BUILD_DIRECTORY=cmake-sonar-build
        CMAKE_COMMAND_LINE_ARGS="-DSONAR=yes"
        MAKE_TARGETS="all test code-quality"

script:
  - mkdir $BUILD_DIRECTORY
  - cd $BUILD_DIRECTORY && cmake $CMAKE_COMMAND_LINE_ARGS ..
  - make $MAKE_TARGETS

after_success:
  # create gcov files
  - find ./CMakeFiles/ -type f -name "*.gcno" -exec gcov {} -m \;
  # upload data to codecav
  - bash <(curl -s https://codecov.io/bash)
